/* THIS IS A PRE-CONFIGURED HACKED config.h for building on windows */

/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */
 
/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
/* #define HAVE_INTTYPES_H 1 */

/* Define to 1 if you have the `krb5_free_keytab_entry_contents' function. */
#define HAVE_KRB5_FREE_KEYTAB_ENTRY_CONTENTS 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
/* #define HAVE_STDINT_H 1 */

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
/* #define HAVE_UNISTD_H 1 */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "webauth-team@lists.stanford.edu"

/* Define to information about when and by whom the package was built. */
#define PACKAGE_BUILD_INFO "Built by schemers@slapshot-xp.stanford.edu on 2003-07-28 21:22:55 UTC"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Webauth"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Webauth 3.2.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "webauth"

/* Define to the version of this package. */
#define PACKAGE_VERSION "3.2.0pre"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to a 4-byte signed type if <inttypes.h> does not define. */
/* #undef int32_t */

/* Define to a 4-byte unsigned type if <inttypes.h> does not define. */
/* #undef uint32_t */
