#!/bin/sh

#
# make a zip of everything needed to run
#

 cd "/cygdrive/c/Program Files/Apache Group/Apache2"

 rm webauth-3.2.0.zip

 zip webauth-3.2.0.zip \
	bin/gssapi32.dll \
	bin/saslGSSAPI.dll \
	bin/libsasl.dll \
	bin/krb5.ini \
	bin/comerr32.dll \
	bin/krb5_32.dll \
	bin/libcurl.dll \
	bin/libeay32.dll \
	bin/ssleay32.dll \
	bin/libwebauth.dll \
	modules/mod_webauth.so \
	modules/mod_webauthldap.so \
	modules/mod_ssl.so \
	conf/stanford-webauth.conf \
	conf/stanford-ldap.conf \
	conf/webauth-ssl.conf \
	conf/webauth/ca-bundle.crt \
	conf/webauth/sasl.reg
