#!/usr/bin/perl
#
# Written by Roland Schemers
# Copyright 2003, 2013
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;
use warnings;

use WebAuth::Tests qw(build_page);

# Set information for the tests.
my %settings;
$settings{test_number} = 4;
$settings{test_desc}   = 'test WebAuthLoginCancelURL';

my @extended = (
    'You have successfully canceled out of logging in and have been sent '
    . 'back to the correct page.');
$settings{extended_desc} = \@extended;

$settings{unauth_location} = 1;

print "Content-type: text/html\n\n";
print build_page(\%settings);
