#!/usr/bin/perl -w
#
# Written by Jon Robertson
# Copyright 2011 Board of Trustees, Leland Stanford Jr. University
#
# See LICENSE for licensing terms.

use strict;

my $REMOTE_USER = $ENV{'REMOTE_USER'};

require '../auth/util.pl';

print "Content-type: text/html\n\n";

print "<html>";

test_title (1, "Any OTP Multifactor test");

print<<EOS;
<p>You are accessing a webauth-protected page as the user: $REMOTE_USER</p>
<p>This test looks for general otp multifactor method working correctly.  It
   requires the user have any otp method to use to log in, in order to view
   this page.</p>
EOS

&return_links;

&multifactor_tests;
&dump_stuff;

print "</html>";

