#!/usr/bin/perl
#
# Written by Jon Robertson
# Copyright 2011, 2013
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;
use warnings;

use WebAuth::Tests qw(build_page);

# Text for the page.
my @extended = (
    'This test tests the workings of multifactor with random multifactor '
    .'set. You should log out and log back in several times to verify that '
    .'you are not normally required to use multifactor.',
);

# Set information for the tests.
my %settings = (
    test_number   => 4,
    test_desc     => 'Random Multifactor test',
    extended_desc => \@extended,
    multifactor   => 1,
);

print "Content-type: text/html\n\n";
print build_page(\%settings);
