#!/usr/bin/perl
#
# Written by Jon Robertson
# Copyright 2011, 2013
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;
use warnings;

use WebAuth::Tests qw(build_page);

# Text for the page.
my @extended = (
    'This test checks the ability of WebAuth to require a session of one of '
    .'two types.  You should be forced to either log back in via a password '
    .'or via a cookie.',
);

# Set information for the tests.
my %settings = (
    test_number   => 14,
    test_desc     => 'Force session with c or p',
    extended_desc => \@extended,
    multifactor   => 1,
);

print "Content-type: text/html\n\n";
print build_page(\%settings);
