#!/usr/bin/perl -w
#
# Written by Jon Robertson
# Copyright 2011 Board of Trustees, Leland Stanford Jr. University
#
# See LICENSE for licensing terms.

use strict;

my $REMOTE_USER = $ENV{'REMOTE_USER'};

require '../auth/util.pl';

print "Content-type: text/html\n\n";

print "<html>";

test_title (1, "Random Multifactor test");

print<<EOS;
<p>You are accessing a webauth-protected page as the user: $REMOTE_USER</p>
<p>This test tests the workings of multifactor with random multifactor set.
   You should log out and log back in several times to verify that you are
   not normally required to use multifactor.</p>
EOS

&return_links;

&multifactor_tests;
&dump_stuff;

print "</html>";

