#!/usr/bin/perl
#
# Written by Jon Robertson
# Copyright 2011, 2013
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;
use warnings;

use WebAuth::Tests qw(build_page);

# Text for the page.
my @extended = (
    'This test checks the ability of WebAuth to require a specific otp '
    .'multifactor method for any users logging in.  In this case we require '
    .'o3.  The meaning of o3 varies from site to site, but is implied to be '
    .'a relatively strong multifactor method.',
);

# Set information for the tests.
my %settings = (
    test_number   => 5,
    test_desc     => 'o50 multifactor',
    extended_desc => \@extended,
    multifactor   => 1,
);

print "Content-type: text/html\n\n";
print build_page(\%settings);
