#!/usr/bin/perl -w
#
# Written by Jon Robertson
# Copyright 2011
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;

my $REMOTE_USER = $ENV{'REMOTE_USER'};

require '../auth/util.pl';

print "Content-type: text/html\n\n";

print "<html>";

test_title (1, "LoA plus o3 test");

print<<EOS;
<p>You are accessing a webauth-protected page as the user: $REMOTE_USER</p>
<p>This test checks the ability of WebAuth to require a specific level of
   assurance for any users logging in, combined with a specific otp method.
   You should only be able to visit the page if you both have a level 3 LoA
   and o3 confitured multifactor.</p>
EOS

&return_links;

&multifactor_tests;
&dump_stuff;

print "</html>";

