#!/usr/bin/perl
#
# Written by Jon Robertson
# Copyright 2011, 2013
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;
use warnings;

use WebAuth::Tests qw(build_page);

# Text for the page.
my @extended = (
    'This test looks for general otp multifactor method working correctly. '
    .'It requires the user have any otp method to use to log in, in order to '
    .'view this page',
);

# Set information for the tests.
my %settings = (
    test_number   => 2,
    test_desc     => 'Any OTP Multifactor test',
    extended_desc => \@extended,
    multifactor   => 1,
);

print "Content-type: text/html\n\n";
print build_page(\%settings);
