#!/usr/bin/perl
#
# Written by Jon Robertson
# Copyright 2011, 2013
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;
use warnings;

use WebAuth::Tests qw(build_page);

# Text for the page.
my @extended = (
    'This test checks the ability of WebAuth to require a specific level of '
    .'assurance for any users logging in.  It is called with an artificially '
    .'high LoA that should deny users from connecting.  If you can see this '
    .'page, something is probably wrong.',
);

# Set information for the tests.
my %settings = (
    test_number   => 9,
    test_desc     => 'Insufficient LoA test',
    extended_desc => \@extended,
    multifactor   => 1,
);

print "Content-type: text/html\n\n";
print build_page(\%settings);
