#!/usr/bin/perl
#
# Written by Jon Robertson
# Copyright 2011, 2013
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;
use warnings;

use WebAuth::Tests qw(build_page);

# Text for the page.
my @extended = (
    'This test checks the ability of WebAuth to force a session login via '
    .'multifactor.  If you were forced to go back through multifactor to '
    .'view this page, it has succeeded.',
);

# Set information for the tests.
my %settings = (
    test_number   => 12,
    test_desc     => 'Force session with multifactor',
    extended_desc => \@extended,
    multifactor   => 1,
);

print "Content-type: text/html\n\n";
print build_page(\%settings);
