#!/usr/bin/perl -w
#
# Written by Jon Robertson
# Copyright 2011
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;

my $REMOTE_USER = $ENV{'REMOTE_USER'};

require '../auth/util.pl';

print "Content-type: text/html\n\n";

print "<html>";

test_title (1, "Force session with multifactor");

print<<EOS;
<p>You are accessing a webauth-protected page as the user: $REMOTE_USER</p>
<p>This test checks the ability of WebAuth to force a session login via
   multifactor.  If you were forced to go back through multifactor to view
   this page, it has succeeded.</p>
EOS

&return_links;

&multifactor_tests;
&dump_stuff;

print "</html>";

