#!/usr/bin/perl -w
#
# Written by Anton Ushakov
# Copyright 2003
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;

my $REMOTE_USER = $ENV{'REMOTE_USER'};
my $AUTHRULE = $ENV{'WEBAUTH_LDAPAUTHRULE'};

require '../util.pl';

print "Content-type: text/html\n\n";

print "<html>";

test_title(4, "legacy directives");

print<<EOS;

You are accessing a webauth-protected page as the user: $REMOTE_USER<br>
<br>
This tests the WebAuth 2.x compatibility directives, <b>AuthType StanfordAuth</b> and <b>require group <i>groupname</i></b>.
<br>
In this case, you have been authorized by "$AUTHRULE" as you can see
 by the environment variable WEBAUTH_LDAPAUTHRULE below.
<br>
EOS

&unauth_return_links;

&dump_stuff;

print "</html>";

