#! /bin/sh

set -e

# Handle module removal.  We can't let dh_apache2 do this for us because we
# have custom postinst tasks.  See the postinst script for more information.
if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
    if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
        . /usr/share/apache2/apache2-maintscript-helper
        apache2_invoke dismod webauth
        apache2_invoke dismod webauthldap
    fi
fi

#DEPHELPER#

exit 0
