#!/bin/sh
#
# Fake remctl backend for WebKDC user metadata queries.  Just returns a stock
# XML file from the data/xml directory based on the command given.

set -e

# Verify that the front-end passed the correct data and determine the XML
# directory to use for responses.
if [ "$1" = "webkdc-info" ] ; then
    dir=info
    if [ "$3" != "127.0.0.1" ] ; then
        echo "invalid IP address $3" >&2
        exit 1
    fi
    if [ "$5" != "0" ] ; then
        echo "invalid random flag $5" >&2
        exit 1
    fi
else
    echo "invalid command $1" >&2
    exit 1
fi

# See if the file exists, and if so, return it.
if [ -f "data/xml/$dir/$2.xml" ] ; then
    exec cat "data/xml/$dir/$2.xml"
else
    echo "unknown user $2" >&2
    exit 1
fi
