#!/usr/bin/perl -w
#
# Written by Roland Schemers
# Copyright 2003 Board of Trustees, Leland Stanford Jr. University
#
# See LICENSE for licensing terms.

use strict;

my $REMOTE_USER = $ENV{'REMOTE_USER'};

require 'util.pl';

print "Content-type: text/html\n\n";

print<<EOS;

<html>

<hr>

Clearing webauth cookie. You should be logged out.
<br>
Click <a href="../index.html">here</a> to return.
EOS

&dump_stuff;

print "</html>";

