#!/usr/bin/perl -w

use strict;

my $REMOTE_USER = $ENV{'REMOTE_USER'};

require 'util.pl';

print "Content-type: text/html\n\n";

print "<html>\n";

test_title(7, "testing 5 second app-token lifetime");

print<<EOS;

You are accessing a webauth-protected page as the user: $REMOTE_USER<br>
<br>
If you are seeing then you might not have run the test correctly.
<br>
<br>
Please logout and run the test again. Make sure to wait 10-15 seconds
before re-running the test after logging in.
<br>
EOS

&return_links;

&dump_stuff;

print "</html>";

