#!/usr/bin/perl
#
# Written by Roland Schemers
# Copyright 2003, 2013
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;
use warnings;

use WebAuth::Tests qw(build_page);

# Text for the page.
my @extended = (
    'If you are seeing this then you might not have run the test correctly.',
    'Please logout and run the test again.  Make sure to wait 10-15 seconds '
                .'before re-running the test after logging in.'
);

# Set information for the tests.
my %settings = (
    test_number   => 7,
    test_desc     => 'testing 5 second app-token lifetime',
    extended_desc => \@extended,
);

print "Content-type: text/html\n\n";
print build_page(\%settings);
