#!/usr/bin/perl -w
#
# Written by Roland Schemers
# Copyright 2003 Board of Trustees, Leland Stanford Jr. University
#
# See LICENSE for licensing terms.

use strict;

my $REMOTE_USER = $ENV{'REMOTE_USER'};

require 'util.pl';

print "Content-type: text/html\n\n";

print "<html>\n";

test_title(3, "testing WebAuthVarPrefix");

print<<EOS;

You are accessing a webauth-protected page as the user: $REMOTE_USER<br>
<br>
This test is to make sure that the WebAuthVarPrefix directive is working. 
<br>
<br>
This
test page has it set to "TEST_", so extra environment variables
that start with "TEST_" should be set in addition to the standard
WebAuth environment variables.
<br>
EOS

&return_links;

&varprefix_tests;

&dump_stuff;

print "</html>";

