#!/usr/bin/perl
#
# Written by Russ Allbery <eagle@eyrie.org>
# Copyright 2003, 2011, 2013
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;
use warnings;

use WebAuth::Tests qw(build_page);

# Text for the page.
my @extended = ('If you are seeing this, the test failed, possibly because '
                .'WebAuthReturnURL was not correctly honored.');

# Set information for the tests.
my %settings = (
    test_number   => 13,
    test_desc     => 'lazy session support',
    extended_desc => \@extended,
);

print "Content-type: text/html\n\n";
print build_page(\%settings);
