#!/usr/bin/perl
#
# Written by Russ Allbery <eagle@eyrie.org>
# Copyright 2014
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;
use warnings;

use WebAuth::Tests qw(build_page);

# Text for the page.
my @extended = ('If you are seeing this you didn\'t run the test correctly.',
                'Please logout and run the test again.');

# Set information for the tests.
my %settings = (
    test_number   => 14,
    test_desc     => 'test cookie path restrictions',
    extended_desc => \@extended,
);

print "Content-type: text/html\n\n";
print build_page(\%settings);
