#!/usr/bin/perl -w
#
# Written by Roland Schemers
# Copyright 2003
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;

my $REMOTE_USER = $ENV{'REMOTE_USER'};

require 'util.pl';

print "Content-type: text/html\n\n";

print "<html>";

test_title(1, "basic WebAuth test");

print<<EOS;

You are accessing a webauth-protected page as the user: $REMOTE_USER<br>
<br>
This test tests the basic ability of WebAuth to protect a page.
<br>
EOS

&return_links;

&dump_stuff;

print "</html>";

