#!/usr/bin/perl -w
#
# Written by Roland Schemers
# Copyright 2003 Board of Trustees, Leland Stanford Jr. University
#
# See LICENSE for licensing terms.

use strict;

my $REMOTE_USER = $ENV{'REMOTE_USER'};

require 'util.pl';

print "Content-type: text/html\n\n";

print "<html>\n";

test_title(2, "testing WebAuthExtraRedirect");

print<<EOS;


You are accessing a webauth-protected page as the user: $REMOTE_USER<br>
<br>
This test is to make sure the WebAuthExtraRedirect directive is working.
This directive causes an extra redirect after initial login, which
causes the browser to re-request the URL and removes all the extra
webauth-related stuff in the URL (the "?WEBAUTHR=...;;WEBAUTHS=...;" stuff
at the end).
<br>
<br>
After an initial login, the URL in the address field of the browser
should not have any query parameters in the URL.
<br>
EOS

&return_links;

&dump_stuff;

print "</html>";

