#!/usr/bin/perl
#
# Written by Roland Schemers
# Copyright 2003, 2013
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;
use warnings;

use WebAuth::Tests qw(build_page);

# Text for the page.
my @extended = ('If are you seeing this, then you returned from a POST '
                .'without authentication to this page and everything is ok!');

# Set information for the tests.
my %settings = (
    test_number   => 12,
    test_desc     => 'test POST with expired cookie',
    extended_desc => \@extended,
);

print "Content-type: text/html\n\n";
print build_page(\%settings);
