#!/usr/bin/perl
#
# Written by Roland Schemers
# Copyright 2003, 2013
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;
use warnings;

use WebAuth::Tests qw(build_page);

# Text for the page.
my @extended = (
    'This test tests the basic ability of WebAuth to protect a page.',
);

# Set information for the tests.
my %settings = (
    test_number   => 1,
    test_desc     => 'basic WebAuth test',
    extended_desc => \@extended,
);

print "Content-type: text/html\n\n";
print build_page(\%settings);
