#!/usr/bin/perl -w
#
# Written by Russ Allbery <rra@stanford.edu>
# Copyright 2003, 2011
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;

my $REMOTE_USER = $ENV{'REMOTE_USER'};

require 'util.pl';

print "Content-type: text/html\n\n";

print "<html>\n";

test_title(12, "test POST with expired cookie");

print<<EOS;
<p>
You are accessing a webauth-protected page as the user: $REMOTE_USER
</p>
<p>
If you are seeing this, the test failed, possibly because WebAuthReturnURL
was not correctly honored.
</p>
EOS

&return_links;

&dump_stuff;

print "</html>";
