#!/usr/pubsw/bin/perl

use strict;
use warnings;

use lib '../bindings/perl/WebAuth/blib/lib';
use lib '../bindings/perl/WebAuth/blib/arch/auto/WebAuth';

use WebAuth qw(:base64 :const :krb5 :key);

use Dumpvalue;

use WebKDC;
use WebKDC::XmlElement;
use WebKDC::XmlDoc;
use WebKDC::Token;
use WebKDC::WebRequest;
use WebKDC::WebResponse;

use Carp;
use UNIVERSAL qw(isa);

use vars qw($CONFIG_WAS_KEYTAB $CONFIG_WAS_KEYRING_PATH);


my $out = new WebKDC::XmlDoc;

$out->start('getTokensRequest');
$out->start('requestCredential', {'type' => 'krb5'});
$out->current->content('{some-base64d-data}<>');
$out->end;
$out->start('tokens');
$out->element('token', {'type'=>'service', 'id'=> 0});
$out->end('tokens');
$out->end('getTokensRequest');

#$dumper->dumpValue($out);

my $xml = $out->root->to_string(1);

print "-------- generated --------\n";
print "$xml\n";
print "-------- generated --------\n";

my $doc = new WebKDC::XmlElement($xml);


print "-------- parsed --------\n";
#my $dumper = new Dumpvalue;
#$dumper->dumpValue($doc);
print $doc->to_string(),"\n";
print "-------- parsed --------\n";

__END__


$out->output();
